### ISSUE TITLE
not working??

### ISSUE THREAD

**Issue by MarshMeadow** [cyyynthia/pronoundb.org#97] opened 2023-05-13 01:07 UTC
not showing up...???

**Comment by NoPlagiarism** [comment] 2023-05-13 02:57
Where?

**Comment by cyyynthia** [comment] 2023-05-13 11:51
You will need to be more specific if you want any help. This kind of issue is absolutely not helpful.

What is not working? What is not showing up? Where is the issue happening? What is the expected behavior?

**Comment by MarshMeadow** [comment] 2023-05-13 16:13
It won't show up on github or discord...

**Comment by cyyynthia** [comment] 2023-05-13 16:47
GitHub has been a bit inconsistent lately but it shows up. I can't reproduce any issue on Discord.

<details>
<summary>Screenshots</summary>

![image](https://github.com/cyyynthia/pronoundb.org/assets/9999055/9894a799-db19-41b6-b2c1-efa6734eb181)
![image](https://github.com/cyyynthia/pronoundb.org/assets/9999055/e37f1400-30da-4778-b1b8-8fd696a4a88c)
![image](https://github.com/cyyynthia/pronoundb.org/assets/9999055/5cc3d251-aba3-4908-95e8-34da0d8dd164)
</details>

**Comment by Benzeel** [comment] 2023-05-18 01:40
i notice it does not work for me both on desktop and mobile (vendetta and vencord) but ONLY works on pc when i use something like a vpn or cloudflare warp (not 1.1.1.1)
i do not know why this happens or what can be done about it other than just using a vpn but this seems to be a sorta? new issue. maybe this is what is happening to the person here. i hope this helps at all

**Comment by cyyynthia** [comment] 2023-05-18 02:11
I do not have any indication on my end of any widespread connectivity issue. Unless your DNS resolver is unable to resolve pronoundb.org, or that your network topology makes it impossible to connect to an OVHcloud IP address, there is no reason for such an issue to occur. (This would mean the PronounDB website should also be entirely unavailable).

I'm also not involved at all in these third party integrations (and have absolutely no interest in knowing more about them), reporting issues here unless you have clear evidence the issue is from the upstream service is not the appropriate place.

Without further information, I can only consider issues of this kind to be issues on your end, with either the integration you're using, or your computer network configuration. I've also seen from time to time in certain scenarios issues with Let's Encrypt TLS certificates caused by the TLS trust chain whatever programs are using, which again isn't a problem on my end that I can resolve.

I'll close this, as there does not seem to have anything actionable here on my end, or any specific guidance I can give for such type of issues.

**Closed as not planned by cyyynthia** 2023-05-18 02:11 UTC
Labels: kind: invalid
