### ISSUE TITLE
Important license questions regarding derivative software

### ISSUE THREAD

**Issue by LizAinslie** [cyyynthia/pronoundb.org#62] opened 2022-06-10 21:56 UTC
Hey :wave:

I just wanted to reach out and talk to you about PronounDB, as I'm making software of slightly derivative concept and have found the work you did on PDB very helpful.

I'd like to credit you fully for the parts I've found most useful, and was wondering how you'd prefer to be credited, whether it be on the site, in the project README, etc. I'm prepared to add licensing information wherever I need as well, I'd just like to also hear your input regarding how I manage that. The project launches in a few weeks and I want to have all my bases covered beforehand.

I'd also like to ask where you found the icon styles for Twitter and Twitch, as I'm trying to replicate a clock in both styles.

If you could reach out to me on Discord `Lizzy A#0016` I'd greatly appreciate it

**Comment by cyyynthia** [comment] 2022-06-10 22:15
hello,

Legally speaking this project is licensed under the permissive BSD-3-Clause license which is a very permissive license. The only requirement is to reproduce/keep the copyright notice where code from this project has been included/modified. That being said, more prominent credits/attributions are welcome and appreciated, while not required.

Icons have been harvested from the websites themselves and "repurposed": Twitter's one is from the "Topics" item when you click on "More" in the sidebar, and Twitch's one is a modified version of the whisper icon, filled instead of simply outlined. Same story for Facebook's and GitHub's, although GitHub was easier due to the publicly available icon pack.

I just explored the interface until I found an icon I found fitting; I can for example suggest for Twitter the icon assigned to the "Languages" item under Settings > Accessibility, which is a planet icon. Last resort remains building the icons yourself and try to match the icon styles 😅

You can find me on my [personal discord server](https://discord.gg/VnxPeNHHpG).

**Comment by LizAinslie** [comment] 2022-06-10 22:40
Thanks, I appreciate it. I'll be adding a licensing page under legal info on the main site listing the parts that used code from PDB and PDB-Powercord, and I'll add some other attribution/linkback on the header of the site. Probably a muted link here:

![screenshot](https://i-work-at-the.cocaine.institute/Lizzy62a3c83bN48ITwpi9oNq.png)

Looking through Twitter/Twitch UI sure sounds fun (not) but it works :P

**Comment by cyyynthia** [comment] 2022-06-10 22:53
I'll close this as resolved then; Just something I'll point out real quick the use of a full TZ name in chat will probably look bulk as hell, maybe consider using `+02:00` format 🙈

**Closed as completed by cyyynthia** 2022-06-10 22:53 UTC
Labels: kind: question

**Comment by LizAinslie** [comment] 2022-06-10 22:57
I have plans to allow users to customize the format of both the current time and the zoneid
