### ISSUE TITLE
Extension Breaks discord "about me"

### ISSUE THREAD

**Issue by Saragon4005** [cyyynthia/pronoundb.org#60] opened 2022-05-05 17:36 UTC
The extension breaks the "About me" section of any user by squeezing the text to the side reducing its length to 1/3rd of its length

How it is with the extension
![Screenshot 2022-05-05 10 30 38](https://user-images.githubusercontent.com/39284711/166980655-eaf55e08-e5aa-4ce8-9ba7-b7dd5a366d89.png)

How it should be (how it is without)
![Screenshot 2022-05-05 10 34 09](https://user-images.githubusercontent.com/39284711/166980740-611dbfd4-f344-479c-aeef-1106de2b4f2a.png)

**Comment by cyyynthia** [comment] 2022-05-05 17:38
Duplicate of #56, see PR #57
Fix has not been pushed to extension stores yet, and additional bugfixes are needed to make a release

**Comment by cyyynthia** [comment] 2022-05-08 22:13
The update (0.9.0) is now available in extension stores

**Closed as completed by cyyynthia** 2022-05-08 22:13 UTC
Labels: kind: bug, kind: duplicate, target: extension
